using System;
using System.Collections.Generic;

namespace MyAPI.Models
{
    public partial class TblRptAcademyFiveHbfb
    {
        public int StuId { get; set; }
        public int? ClassId { get; set; }
        public string? Section { get; set; }
        public int? Wing { get; set; }
        public string? Paper1Name { get; set; }
        public int? Paper1Total { get; set; }
        public int? Paper1Slot1 { get; set; }
        public int? Paper1Slot2 { get; set; }
        public int? Paper1Slot3 { get; set; }
        public int? Paper1Slot4 { get; set; }
        public int? Paper1Slot5 { get; set; }
        public int? Paper1Hb1 { get; set; }
        public int? Paper1Hb2 { get; set; }
        public int? Paper1Fb { get; set; }
        public string? Paper2Name { get; set; }
        public int? Paper2Total { get; set; }
        public int? Paper2Slot1 { get; set; }
        public int? Paper2Slot2 { get; set; }
        public int? Paper2Slot3 { get; set; }
        public int? Paper2Slot4 { get; set; }
        public int? Paper2Slot5 { get; set; }
        public int? Paper2Hb1 { get; set; }
        public int? Paper2Hb2 { get; set; }
        public int? Paper2Fb { get; set; }
        public string? Paper3Name { get; set; }
        public int? Paper3Total { get; set; }
        public int? Paper3Slot1 { get; set; }
        public int? Paper3Slot2 { get; set; }
        public int? Paper3Slot3 { get; set; }
        public int? Paper3Slot4 { get; set; }
        public int? Paper3Slot5 { get; set; }
        public int? Paper3Hb1 { get; set; }
        public int? Paper3Hb2 { get; set; }
        public int? Paper3Fb { get; set; }
        public string? Paper4Name { get; set; }
        public int? Paper4Total { get; set; }
        public int? Paper4Slot1 { get; set; }
        public int? Paper4Slot2 { get; set; }
        public int? Paper4Slot3 { get; set; }
        public int? Paper4Slot4 { get; set; }
        public int? Paper4Slot5 { get; set; }
        public int? Paper4Hb1 { get; set; }
        public int? Paper4Hb2 { get; set; }
        public int? Paper4Fb { get; set; }
        public string? Paper5Name { get; set; }
        public int? Paper5Total { get; set; }
        public int? Paper5Slot1 { get; set; }
        public int? Paper5Slot2 { get; set; }
        public int? Paper5Slot3 { get; set; }
        public int? Paper5Slot4 { get; set; }
        public int? Paper5Slot5 { get; set; }
        public int? Paper5Hb1 { get; set; }
        public int? Paper5Hb2 { get; set; }
        public int? Paper5Fb { get; set; }
        public string? Paper6Name { get; set; }
        public int? Paper6Total { get; set; }
        public int? Paper6Slot1 { get; set; }
        public int? Paper6Slot2 { get; set; }
        public int? Paper6Slot3 { get; set; }
        public int? Paper6Slot4 { get; set; }
        public int? Paper6Slot5 { get; set; }
        public int? Paper6Hb1 { get; set; }
        public int? Paper6Hb2 { get; set; }
        public int? Paper6Fb { get; set; }
        public string? Paper7Name { get; set; }
        public int? Paper7Total { get; set; }
        public int? Paper7Slot1 { get; set; }
        public int? Paper7Slot2 { get; set; }
        public int? Paper7Slot3 { get; set; }
        public int? Paper7Slot4 { get; set; }
        public int? Paper7Slot5 { get; set; }
        public int? Paper7Hb1 { get; set; }
        public int? Paper7Hb2 { get; set; }
        public int? Paper7Fb { get; set; }
        public string? Paper8Name { get; set; }
        public int? Paper8Total { get; set; }
        public int? Paper8Slot1 { get; set; }
        public int? Paper8Slot2 { get; set; }
        public int? Paper8Slot3 { get; set; }
        public int? Paper8Slot4 { get; set; }
        public int? Paper8Slot5 { get; set; }
        public int? Paper8Hb1 { get; set; }
        public int? Paper8Hb2 { get; set; }
        public int? Paper8Fb { get; set; }
        public string? Paper9Name { get; set; }
        public int? Paper9Total { get; set; }
        public int? Paper9Slot1 { get; set; }
        public int? Paper9Slot2 { get; set; }
        public int? Paper9Slot3 { get; set; }
        public int? Paper9Slot4 { get; set; }
        public int? Paper9Slot5 { get; set; }
        public int? Paper9Hb1 { get; set; }
        public int? Paper9Hb2 { get; set; }
        public int? Paper9Fb { get; set; }
        public string? Paper10Name { get; set; }
        public int? Paper10Total { get; set; }
        public int? Paper10Slot1 { get; set; }
        public int? Paper10Slot2 { get; set; }
        public int? Paper10Slot3 { get; set; }
        public int? Paper10Slot4 { get; set; }
        public int? Paper10Slot5 { get; set; }
        public int? Paper10Hb1 { get; set; }
        public int? Paper10Hb2 { get; set; }
        public int? Paper10Fb { get; set; }
        public string? Paper11Name { get; set; }
        public int? Paper11Total { get; set; }
        public int? Paper11Slot1 { get; set; }
        public int? Paper11Slot2 { get; set; }
        public int? Paper11Slot3 { get; set; }
        public int? Paper11Slot4 { get; set; }
        public int? Paper11Slot5 { get; set; }
        public int? Paper11Hb1 { get; set; }
        public int? Paper11Hb2 { get; set; }
        public int? Paper11Fb { get; set; }
        public string? Paper12Name { get; set; }
        public int? Paper12Total { get; set; }
        public int? Paper12Slot1 { get; set; }
        public int? Paper12Slot2 { get; set; }
        public int? Paper12Slot3 { get; set; }
        public int? Paper12Slot4 { get; set; }
        public int? Paper12Slot5 { get; set; }
        public int? Paper12Hb1 { get; set; }
        public int? Paper12Hb2 { get; set; }
        public int? Paper12Fb { get; set; }
        public string? Paper13Name { get; set; }
        public int? Paper13Total { get; set; }
        public int? Paper13Slot1 { get; set; }
        public int? Paper13Slot2 { get; set; }
        public int? Paper13Slot3 { get; set; }
        public int? Paper13Slot4 { get; set; }
        public int? Paper13Slot5 { get; set; }
        public int? Paper13Hb1 { get; set; }
        public int? Paper13Hb2 { get; set; }
        public int? Paper13Fb { get; set; }
        public string? Paper14Name { get; set; }
        public int? Paper14Total { get; set; }
        public int? Paper14Slot1 { get; set; }
        public int? Paper14Slot2 { get; set; }
        public int? Paper14Slot3 { get; set; }
        public int? Paper14Slot4 { get; set; }
        public int? Paper14Slot5 { get; set; }
        public int? Paper14Hb1 { get; set; }
        public int? Paper14Hb2 { get; set; }
        public int? Paper14Fb { get; set; }
        public int? TotalMarks { get; set; }
        public int? TotalSlot1 { get; set; }
        public int? TotalSlot2 { get; set; }
        public int? TotalSlot3 { get; set; }
        public int? TotalSlot4 { get; set; }
        public int? TotalSlot5 { get; set; }
        public int? TotalHb1 { get; set; }
        public int? TotalHb2 { get; set; }
        public int? TotalFb2 { get; set; }
        public string? GradeSlot1 { get; set; }
        public string? GradeSlot2 { get; set; }
        public string? GradeSlot3 { get; set; }
        public string? GradeSlot4 { get; set; }
        public string? GradeSlot5 { get; set; }
        public string? GradeHb1 { get; set; }
        public string? GradeHb2 { get; set; }
        public string? GradeFb { get; set; }
    }
}
