using System;
using System.Collections.Generic;

namespace MyAPI.Models
{
    public partial class TblRptAcademyThreePlusThree
    {
        public int StuId { get; set; }
        public int? ClassId { get; set; }
        public string? Section { get; set; }
        public int? Wing { get; set; }
        public string? Paper1Name { get; set; }
        public int? Paper1Total { get; set; }
        public int? Paper1Slot1 { get; set; }
        public int? Paper1Slot2 { get; set; }
        public int? Paper1Slot3 { get; set; }
        public int? Paper1Sec2Total { get; set; }
        public int? Paper1Sec2Slot1 { get; set; }
        public int? Paper1Sec2Slot2 { get; set; }
        public int? Paper1Sec2Slot3 { get; set; }
        public string? Paper2Name { get; set; }
        public int? Paper2Total { get; set; }
        public int? Paper2Slot1 { get; set; }
        public int? Paper2Slot2 { get; set; }
        public int? Paper2Slot3 { get; set; }
        public int? Paper2Sec2Total { get; set; }
        public int? Paper2Sec2Slot1 { get; set; }
        public int? Paper2Sec2Slot2 { get; set; }
        public int? Paper2Sec2Slot3 { get; set; }
        public string? Paper3Name { get; set; }
        public int? Paper3Total { get; set; }
        public int? Paper3Slot1 { get; set; }
        public int? Paper3Slot2 { get; set; }
        public int? Paper3Slot3 { get; set; }
        public int? Paper3Sec2Total { get; set; }
        public int? Paper3Sec2Slot1 { get; set; }
        public int? Paper3Sec2Slot2 { get; set; }
        public int? Paper3Sec2Slot3 { get; set; }
        public string? Paper4Name { get; set; }
        public int? Paper4Total { get; set; }
        public int? Paper4Slot1 { get; set; }
        public int? Paper4Slot2 { get; set; }
        public int? Paper4Slot3 { get; set; }
        public int? Paper4Sec2Total { get; set; }
        public int? Paper4Sec2Slot1 { get; set; }
        public int? Paper4Sec2Slot2 { get; set; }
        public int? Paper4Sec2Slot3 { get; set; }
        public string? Paper5Name { get; set; }
        public int? Paper5Total { get; set; }
        public int? Paper5Slot1 { get; set; }
        public int? Paper5Slot2 { get; set; }
        public int? Paper5Slot3 { get; set; }
        public int? Paper5Sec2Total { get; set; }
        public int? Paper5Sec2Slot1 { get; set; }
        public int? Paper5Sec2Slot2 { get; set; }
        public int? Paper5Sec2Slot3 { get; set; }
        public string? Paper6Name { get; set; }
        public int? Paper6Total { get; set; }
        public int? Paper6Slot1 { get; set; }
        public int? Paper6Slot2 { get; set; }
        public int? Paper6Slot3 { get; set; }
        public int? Paper6Sec2Total { get; set; }
        public int? Paper6Sec2Slot1 { get; set; }
        public int? Paper6Sec2Slot2 { get; set; }
        public int? Paper6Sec2Slot3 { get; set; }
        public string? Paper7Name { get; set; }
        public int? Paper7Total { get; set; }
        public int? Paper7Slot1 { get; set; }
        public int? Paper7Slot2 { get; set; }
        public int? Paper7Slot3 { get; set; }
        public int? Paper7Sec2Total { get; set; }
        public int? Paper7Sec2Slot1 { get; set; }
        public int? Paper7Sec2Slot2 { get; set; }
        public int? Paper7Sec2Slot3 { get; set; }
        public string? Paper8Name { get; set; }
        public int? Paper8Total { get; set; }
        public int? Paper8Slot1 { get; set; }
        public int? Paper8Slot2 { get; set; }
        public int? Paper8Slot3 { get; set; }
        public int? Paper8Sec2Total { get; set; }
        public int? Paper8Sec2Slot1 { get; set; }
        public int? Paper8Sec2Slot2 { get; set; }
        public int? Paper8Sec2Slot3 { get; set; }
        public string? Paper9Name { get; set; }
        public int? Paper9Total { get; set; }
        public int? Paper9Slot1 { get; set; }
        public int? Paper9Slot2 { get; set; }
        public int? Paper9Slot3 { get; set; }
        public int? Paper9Sec2Total { get; set; }
        public int? Paper9Sec2Slot1 { get; set; }
        public int? Paper9Sec2Slot2 { get; set; }
        public int? Paper9Sec2Slot3 { get; set; }
        public string? Paper10Name { get; set; }
        public int? Paper10Total { get; set; }
        public int? Paper10Slot1 { get; set; }
        public int? Paper10Slot2 { get; set; }
        public int? Paper10Slot3 { get; set; }
        public int? Paper10Sec2Total { get; set; }
        public int? Paper10Sec2Slot1 { get; set; }
        public int? Paper10Sec2Slot2 { get; set; }
        public int? Paper10Sec2Slot3 { get; set; }
        public string? Paper11Name { get; set; }
        public int? Paper11Total { get; set; }
        public int? Paper11Slot1 { get; set; }
        public int? Paper11Slot2 { get; set; }
        public int? Paper11Slot3 { get; set; }
        public int? Paper11Sec2Total { get; set; }
        public int? Paper11Sec2Slot1 { get; set; }
        public int? Paper11Sec2Slot2 { get; set; }
        public int? Paper11Sec2Slot3 { get; set; }
        public string? Paper12Name { get; set; }
        public int? Paper12Total { get; set; }
        public int? Paper12Slot1 { get; set; }
        public int? Paper12Slot2 { get; set; }
        public int? Paper12Slot3 { get; set; }
        public int? Paper12Sec2Total { get; set; }
        public int? Paper12Sec2Slot1 { get; set; }
        public int? Paper12Sec2Slot2 { get; set; }
        public int? Paper12Sec2Slot3 { get; set; }
        public string? Paper13Name { get; set; }
        public int? Paper13Total { get; set; }
        public int? Paper13Slot1 { get; set; }
        public int? Paper13Slot2 { get; set; }
        public int? Paper13Slot3 { get; set; }
        public int? Paper13Sec2Total { get; set; }
        public int? Paper13Sec2Slot1 { get; set; }
        public int? Paper13Sec2Slot2 { get; set; }
        public int? Paper13Sec2Slot3 { get; set; }
        public string? Paper14Name { get; set; }
        public int? Paper14Total { get; set; }
        public int? Paper14Slot1 { get; set; }
        public int? Paper14Slot2 { get; set; }
        public int? Paper14Slot3 { get; set; }
        public int? Paper14Sec2Total { get; set; }
        public int? Paper14Sec2Slot1 { get; set; }
        public int? Paper14Sec2Slot2 { get; set; }
        public int? Paper14Sec2Slot3 { get; set; }
        public int? TotalMarks { get; set; }
        public int? TotalSlot1 { get; set; }
        public int? TotalSlot2 { get; set; }
        public int? TotalSlot3 { get; set; }
        public int? TotalSec2Marks { get; set; }
        public int? TotalSec2Slot1 { get; set; }
        public int? TotalSec2Slot2 { get; set; }
        public int? TotalSec2Slot3 { get; set; }
        public string? GradeSlot1 { get; set; }
        public string? GradeSlot2 { get; set; }
        public string? GradeSlot3 { get; set; }
        public string? GradeSec2Slot1 { get; set; }
        public string? GradeSec2Slot2 { get; set; }
        public string? GradeSec2Slot3 { get; set; }
        public string? PositionSlot1 { get; set; }
        public string? PositionSlot2 { get; set; }
        public string? PositionSlot3 { get; set; }
        public string? PositionSec2Slot1 { get; set; }
        public string? PositionSec2Slot2 { get; set; }
        public string? PositionSec2Slot3 { get; set; }
        public string? Remarks { get; set; }
    }
}
