using System;
using System.Collections.Generic;

namespace MyAPI.Models
{
    public partial class ViewAcademyResult
    {
        public string? StuRegNumber { get; set; }
        public string StuName { get; set; } = null!;
        public string ClassName { get; set; } = null!;
        public int StuId { get; set; }
        public int? ClassId { get; set; }
        public string? Section { get; set; }
        public int? Wing { get; set; }
        public string? Paper1Name { get; set; }
        public int? Paper1Total { get; set; }
        public int? Paper1Slot1 { get; set; }
        public int? Paper1Slot2 { get; set; }
        public int? Paper1Slot3 { get; set; }
        public int? Paper1Slot4 { get; set; }
        public int? Paper1Slot5 { get; set; }
        public int? Paper1Slot6 { get; set; }
        public int? Paper1Slot7 { get; set; }
        public string? Paper2Name { get; set; }
        public int? Paper2Total { get; set; }
        public int? Paper2Slot1 { get; set; }
        public int? Paper2Slot2 { get; set; }
        public int? Paper2Slot3 { get; set; }
        public int? Paper2Slot4 { get; set; }
        public int? Paper2Slot5 { get; set; }
        public int? Paper2Slot6 { get; set; }
        public int? Paper2Slot7 { get; set; }
        public string? Paper3Name { get; set; }
        public int? Paper3Total { get; set; }
        public int? Paper3Slot1 { get; set; }
        public int? Paper3Slot2 { get; set; }
        public int? Paper3Slot3 { get; set; }
        public int? Paper3Slot4 { get; set; }
        public int? Paper3Slot5 { get; set; }
        public int? Paper3Slot6 { get; set; }
        public int? Paper3Slot7 { get; set; }
        public string? Paper4Name { get; set; }
        public int? Paper4Total { get; set; }
        public int? Paper4Slot1 { get; set; }
        public int? Paper4Slot2 { get; set; }
        public int? Paper4Slot3 { get; set; }
        public int? Paper4Slot4 { get; set; }
        public int? Paper4Slot5 { get; set; }
        public int? Paper4Slot6 { get; set; }
        public int? Paper4Slot7 { get; set; }
        public string? Paper5Name { get; set; }
        public int? Paper5Total { get; set; }
        public int? Paper5Slot1 { get; set; }
        public int? Paper5Slot2 { get; set; }
        public int? Paper5Slot3 { get; set; }
        public int? Paper5Slot4 { get; set; }
        public int? Paper5Slot5 { get; set; }
        public int? Paper5Slot6 { get; set; }
        public int? Paper5Slot7 { get; set; }
        public string? Paper6Name { get; set; }
        public int? Paper6Total { get; set; }
        public int? Paper6Slot1 { get; set; }
        public int? Paper6Slot2 { get; set; }
        public int? Paper6Slot3 { get; set; }
        public int? Paper6Slot4 { get; set; }
        public int? Paper6Slot5 { get; set; }
        public int? Paper6Slot6 { get; set; }
        public int? Paper6Slot7 { get; set; }
        public string? Paper7Name { get; set; }
        public int? Paper7Total { get; set; }
        public int? Paper7Slot1 { get; set; }
        public int? Paper7Slot2 { get; set; }
        public int? Paper7Slot3 { get; set; }
        public int? Paper7Slot4 { get; set; }
        public int? Paper7Slot5 { get; set; }
        public int? Paper7Slot6 { get; set; }
        public int? Paper7Slot7 { get; set; }
        public string? Paper8Name { get; set; }
        public int? Paper8Total { get; set; }
        public int? Paper8Slot1 { get; set; }
        public int? Paper8Slot2 { get; set; }
        public int? Paper8Slot3 { get; set; }
        public int? Paper8Slot4 { get; set; }
        public int? Paper8Slot5 { get; set; }
        public int? Paper8Slot6 { get; set; }
        public int? Paper8Slot7 { get; set; }
        public string? Paper9Name { get; set; }
        public int? Paper9Total { get; set; }
        public int? Paper9Slot1 { get; set; }
        public int? Paper9Slot2 { get; set; }
        public int? Paper9Slot3 { get; set; }
        public int? Paper9Slot4 { get; set; }
        public int? Paper9Slot5 { get; set; }
        public int? Paper9Slot6 { get; set; }
        public int? Paper9Slot7 { get; set; }
        public string? Paper10Name { get; set; }
        public int? Paper10Total { get; set; }
        public int? Paper10Slot1 { get; set; }
        public int? Paper10Slot2 { get; set; }
        public int? Paper10Slot3 { get; set; }
        public int? Paper10Slot4 { get; set; }
        public int? Paper10Slot5 { get; set; }
        public int? Paper10Slot6 { get; set; }
        public int? Paper10Slot7 { get; set; }
        public string? Paper11Name { get; set; }
        public int? Paper11Total { get; set; }
        public int? Paper11Slot1 { get; set; }
        public int? Paper11Slot2 { get; set; }
        public int? Paper11Slot3 { get; set; }
        public int? Paper11Slot4 { get; set; }
        public int? Paper11Slot5 { get; set; }
        public int? Paper11Slot6 { get; set; }
        public int? Paper11Slot7 { get; set; }
        public string? Paper12Name { get; set; }
        public int? Paper12Total { get; set; }
        public int? Paper12Slot1 { get; set; }
        public int? Paper12Slot2 { get; set; }
        public int? Paper12Slot3 { get; set; }
        public int? Paper12Slot4 { get; set; }
        public int? Paper12Slot5 { get; set; }
        public int? Paper12Slot6 { get; set; }
        public int? Paper12Slot7 { get; set; }
        public string? Paper13Name { get; set; }
        public int? Paper13Total { get; set; }
        public int? Paper13Slot1 { get; set; }
        public int? Paper13Slot2 { get; set; }
        public int? Paper13Slot3 { get; set; }
        public int? Paper13Slot4 { get; set; }
        public int? Paper13Slot5 { get; set; }
        public int? Paper13Slot6 { get; set; }
        public int? Paper13Slot7 { get; set; }
        public string? Paper14Name { get; set; }
        public int? Paper14Total { get; set; }
        public int? Paper14Slot1 { get; set; }
        public int? Paper14Slot2 { get; set; }
        public int? Paper14Slot3 { get; set; }
        public int? Paper14Slot4 { get; set; }
        public int? Paper14Slot5 { get; set; }
        public int? Paper14Slot6 { get; set; }
        public int? Paper14Slot7 { get; set; }
        public int? TotalMarks { get; set; }
        public int? TotalSlot1 { get; set; }
        public int? TotalSlot2 { get; set; }
        public int? TotalSlot3 { get; set; }
        public int? TotalSlot4 { get; set; }
        public int? TotalSlot5 { get; set; }
        public int? TotalSlot6 { get; set; }
        public int? TotalSlot7 { get; set; }
        public string? GradeSlot1 { get; set; }
        public string? GradeSlot2 { get; set; }
        public string? GradeSlot3 { get; set; }
        public string? GradeSlot4 { get; set; }
        public string? GradeSlot5 { get; set; }
        public string? GradeSlot6 { get; set; }
        public string? GradeSlot7 { get; set; }
        public string? PositionSlot1 { get; set; }
        public string? PositionSlot2 { get; set; }
        public string? PositionSlot3 { get; set; }
        public string? PositionSlot4 { get; set; }
        public string? PositionSlot5 { get; set; }
        public string? PositionSlot6 { get; set; }
        public string? PositionSlot7 { get; set; }
        public string? Remarks { get; set; }
        public string? PercSlot1 { get; set; }
        public string? PercSlot2 { get; set; }
        public string? PercSlot3 { get; set; }
        public string? PercSlot4 { get; set; }
        public string? PercSlot5 { get; set; }
        public string? PercSlot6 { get; set; }
        public string? PercSlot7 { get; set; }
    }
}
