using System;
using System.Collections.Generic;

namespace MyAPI.Models
{
    public partial class ViewResultTestSeries
    {
        public string ClassName { get; set; } = null!;
        public string? StuRegNumber { get; set; }
        public string StuName { get; set; } = null!;
        public int StuId { get; set; }
        public int ClassId { get; set; }
        public int EnglishTotal { get; set; }
        public int EnglishSlot1 { get; set; }
        public int EnglishSlot2 { get; set; }
        public int EnglishSlot3 { get; set; }
        public int EnglishSlot4 { get; set; }
        public int EnglishSlot5 { get; set; }
        public int EnglishTotalHalfFull { get; set; }
        public int EnglishHalfBook1 { get; set; }
        public int EnglishHalfBook2 { get; set; }
        public int EnglishFullBook { get; set; }
        public int UrduTotal { get; set; }
        public int UrduSlot1 { get; set; }
        public int UrduSlot2 { get; set; }
        public int UrduSlot3 { get; set; }
        public int UrduSlot4 { get; set; }
        public int UrduSlot5 { get; set; }
        public int UrduTotalHalfFull { get; set; }
        public int UrduHalfBook1 { get; set; }
        public int UrduHalfBook2 { get; set; }
        public int UrduFullBook { get; set; }
        public int ArabicTotal { get; set; }
        public int ArabicSlot1 { get; set; }
        public int ArabicSlot2 { get; set; }
        public int ArabicSlot3 { get; set; }
        public int ArabicSlot4 { get; set; }
        public int ArabicSlot5 { get; set; }
        public int ArabicTotalHalfFull { get; set; }
        public int ArabicHalfBook1 { get; set; }
        public int ArabicHalfBook2 { get; set; }
        public int ArabicFullBook { get; set; }
        public int MathematicsTotal { get; set; }
        public int MathematicsSlot1 { get; set; }
        public int MathematicsSlot2 { get; set; }
        public int MathematicsSlot3 { get; set; }
        public int MathematicsSlot4 { get; set; }
        public int MathematicsSlot5 { get; set; }
        public int MathematicsTotalHalfFull { get; set; }
        public int MathematicsHalfBook1 { get; set; }
        public int MathematicsHalfBook2 { get; set; }
        public int MathematicsFullBook { get; set; }
        public int ScienceTotal { get; set; }
        public int ScienceSlot1 { get; set; }
        public int ScienceSlot2 { get; set; }
        public int ScienceSlot3 { get; set; }
        public int ScienceSlot4 { get; set; }
        public int ScienceSlot5 { get; set; }
        public int ScienceTotalHalfFull { get; set; }
        public int ScienceHalfBook1 { get; set; }
        public int ScienceHalfBook2 { get; set; }
        public int ScienceFullBook { get; set; }
        public int SocialStudiesTotal { get; set; }
        public int SocialStudiesSlot1 { get; set; }
        public int SocialStudiesSlot2 { get; set; }
        public int SocialStudiesSlot3 { get; set; }
        public int SocialStudiesSlot4 { get; set; }
        public int SocialStudiesSlot5 { get; set; }
        public int SocialStudiesTotalHalfFull { get; set; }
        public int SocialStudiesHalfBook1 { get; set; }
        public int SocialStudiesHalfBook2 { get; set; }
        public int SocialStudiesFullBook { get; set; }
        public int IslamiatTotal { get; set; }
        public int IslamiatSlot1 { get; set; }
        public int IslamiatSlot2 { get; set; }
        public int IslamiatSlot3 { get; set; }
        public int IslamiatSlot4 { get; set; }
        public int IslamiatSlot5 { get; set; }
        public int IslamiatTotalHalfFull { get; set; }
        public int IslamiatHalfBook1 { get; set; }
        public int IslamiatHalfBook2 { get; set; }
        public int IslamiatFullBook { get; set; }
        public int ComputerTotal { get; set; }
        public int ComputerSlot1 { get; set; }
        public int ComputerSlot2 { get; set; }
        public int ComputerSlot3 { get; set; }
        public int ComputerSlot4 { get; set; }
        public int ComputerSlot5 { get; set; }
        public int ComputerTotalHalfFull { get; set; }
        public int ComputerHalfBook1 { get; set; }
        public int ComputerHalfBook2 { get; set; }
        public int ComputerFullBook { get; set; }
        public int PhysicsTotal { get; set; }
        public int PhysicsSlot1 { get; set; }
        public int PhysicsSlot2 { get; set; }
        public int PhysicsSlot3 { get; set; }
        public int PhysicsSlot4 { get; set; }
        public int PhysicsSlot5 { get; set; }
        public int PhysicsTotalHalfFull { get; set; }
        public int PhysicsHalfBook1 { get; set; }
        public int PhysicsHalfBook2 { get; set; }
        public int PhysicsFullBook { get; set; }
        public int QuranTotal { get; set; }
        public int QuranSlot1 { get; set; }
        public int QuranSlot2 { get; set; }
        public int QuranSlot3 { get; set; }
        public int QuranSlot4 { get; set; }
        public int QuranSlot5 { get; set; }
        public int QuranTotalHalfFull { get; set; }
        public int QuranHalfBook1 { get; set; }
        public int QuranHalfBook2 { get; set; }
        public int QuranFullBook { get; set; }
        public int BehaviorSlot1 { get; set; }
        public int BehaviorSlot2 { get; set; }
        public int BehaviorSlot3 { get; set; }
        public int BehaviorSlot4 { get; set; }
        public int BehaviorSlot5 { get; set; }
        public int BehaviorTotal { get; set; }
        public int BehaviorTotalHalfFull { get; set; }
        public int BehaviorHalfBook1 { get; set; }
        public int BehaviorHalfBook2 { get; set; }
        public int BehaviorFullBook { get; set; }
        public int ChemistryTotal { get; set; }
        public int ChemistrySlot1 { get; set; }
        public int ChemistrySlot2 { get; set; }
        public int ChemistrySlot3 { get; set; }
        public int ChemistrySlot4 { get; set; }
        public int ChemistrySlot5 { get; set; }
        public int ChemistryTotalHalfFull { get; set; }
        public int ChemistryHalfBook1 { get; set; }
        public int ChemistryHalfBook2 { get; set; }
        public int ChemistryFullBook { get; set; }
        public int BiologyTotal { get; set; }
        public int BiologySlot1 { get; set; }
        public int BiologySlot2 { get; set; }
        public int BiologySlot3 { get; set; }
        public int BiologySlot4 { get; set; }
        public int BiologySlot5 { get; set; }
        public int BiologyTotalHalfFull { get; set; }
        public int BiologyHalfBook1 { get; set; }
        public int BiologyHalfBook2 { get; set; }
        public int BiologyFullBook { get; set; }
        public int AgriHeconomicsTotal { get; set; }
        public int AgriHeconomicsSlot1 { get; set; }
        public int AgriHeconomicsSlot2 { get; set; }
        public int AgriHeconomicsSlot3 { get; set; }
        public int? AgriHeconomicsSlot4 { get; set; }
        public int? AgriHeconomicsSlot5 { get; set; }
        public int? AgriHeconomicsTotalHalfFull { get; set; }
        public int? AgriHeconomicsHalfBook1 { get; set; }
        public int? AgriHeconomicsHalfBook2 { get; set; }
        public int? AgriHeconomicsFullBook { get; set; }
        public int? Total { get; set; }
        public int? TotalSlot1 { get; set; }
        public int? TotalSlot2 { get; set; }
        public int? TotalSlot3 { get; set; }
        public int? TotalSlot4 { get; set; }
        public int? TotalSlot5 { get; set; }
        public string? GradeSlot1 { get; set; }
        public string? GradeSlot2 { get; set; }
        public string? GradeSlot3 { get; set; }
        public string? GradeSlot4 { get; set; }
        public string? GradeSlot5 { get; set; }
        public int? PositionSlot1 { get; set; }
        public int? PositionSlot2 { get; set; }
        public int? PositionSlot3 { get; set; }
        public int? PositionSlot4 { get; set; }
        public int? PositionSlot5 { get; set; }
        public int? TotalHalfFull { get; set; }
        public int? TotalHalfBook1 { get; set; }
        public int? TotalHalfBook2 { get; set; }
        public int? TotalFullBook { get; set; }
        public string? GradeHalfBook1 { get; set; }
        public string? GradeHalfBook2 { get; set; }
        public string? GradeFullBook { get; set; }
        public int? PositionHalfBook1 { get; set; }
        public int? PositionHalfBook2 { get; set; }
        public int? PositionFullBook { get; set; }
        public string? Remarks { get; set; }
        public string? StuGender { get; set; }
        public int? StuCurrentWing { get; set; }
    }
}
