using System;
using System.Collections.Generic;

namespace MyAPI.Models
{
    public partial class ViewAggregateResult
    {
        public int StuId { get; set; }
        public int ClassId { get; set; }
        public int? Wing { get; set; }
        public int? EnglishTotal { get; set; }
        public int? EnglishSlot1 { get; set; }
        public int? EnglishSlot2 { get; set; }
        public int? EnglishSlot3 { get; set; }
        public int? UrduTotal { get; set; }
        public int? UrduSlot1 { get; set; }
        public int? UrduSlot2 { get; set; }
        public int? UrduSlot3 { get; set; }
        public int? ArabicTotal { get; set; }
        public int? ArabicSlot1 { get; set; }
        public int? ArabicSlot2 { get; set; }
        public int? ArabicSlot3 { get; set; }
        public int? MathematicsTotal { get; set; }
        public int? MathematicsSlot1 { get; set; }
        public int? MathematicsSlot2 { get; set; }
        public int? MathematicsSlot3 { get; set; }
        public int? ScienceTotal { get; set; }
        public int? ScienceSlot1 { get; set; }
        public int? ScienceSlot2 { get; set; }
        public int? ScienceSlot3 { get; set; }
        public int? SocialStudiesTotal { get; set; }
        public int? SocialStudiesSlot1 { get; set; }
        public int? SocialStudiesSlot2 { get; set; }
        public int? SocialStudiesSlot3 { get; set; }
        public int? IslamiatTotal { get; set; }
        public int? IslamiatSlot1 { get; set; }
        public int? IslamiatSlot2 { get; set; }
        public int? IslamiatSlot3 { get; set; }
        public int? ComputerTotal { get; set; }
        public int? ComputerSlot1 { get; set; }
        public int? ComputerSlot2 { get; set; }
        public int? ComputerSlot3 { get; set; }
        public int? QuranTotal { get; set; }
        public int? QuranSlot1 { get; set; }
        public int? QuranSlot2 { get; set; }
        public int? QuranSlot3 { get; set; }
        public int? BehaviorTotal { get; set; }
        public int? BehaviorSlot1 { get; set; }
        public int? BehaviorSlot2 { get; set; }
        public int? BehaviorSlot3 { get; set; }
        public int? PhysicsTotal { get; set; }
        public int? PhysicsSlot1 { get; set; }
        public int? PhysicsSlot2 { get; set; }
        public int? PhysicsSlot3 { get; set; }
        public int? ChemistryTotal { get; set; }
        public int? ChemistrySlot1 { get; set; }
        public int? ChemistrySlot2 { get; set; }
        public int? ChemistrySlot3 { get; set; }
        public int? BiologyTotal { get; set; }
        public int? BiologySlot1 { get; set; }
        public int? BiologySlot2 { get; set; }
        public int? BiologySlot3 { get; set; }
        public int? AgriHeconomicsTotal { get; set; }
        public int? AgriHeconomicsSlot1 { get; set; }
        public int? AgriHeconomicsSlot2 { get; set; }
        public int? AgriHeconomicsSlot3 { get; set; }
        public int? EnglishTermTotal { get; set; }
        public int? EnglishTerm { get; set; }
        public int? UrduTermTotal { get; set; }
        public int? UrduTerm { get; set; }
        public int? ArabicTermTotal { get; set; }
        public int? ArabicTerm { get; set; }
        public int? MathematicsTermTotal { get; set; }
        public int? MathematicsTerm { get; set; }
        public int? ScienceTermTotal { get; set; }
        public int? ScienceTerm { get; set; }
        public int? SocialStudiesTermTotal { get; set; }
        public int? SocialStudiesTerm { get; set; }
        public int? IslamiatTermTotal { get; set; }
        public int? IslamiatTerm { get; set; }
        public int? ComputerTermTotal { get; set; }
        public int? ComputerTerm { get; set; }
        public int? QuranTermTotal { get; set; }
        public int? QuranTerm { get; set; }
        public int? BehaviorTermTotal { get; set; }
        public int? BehaviorTerm { get; set; }
        public int? PhysicsTermTotal { get; set; }
        public int? PhysicsTerm { get; set; }
        public int? ChemistryTermTotal { get; set; }
        public int? ChemistryTerm { get; set; }
        public int? BiologyTermTotal { get; set; }
        public int? BiologyTerm { get; set; }
        public int? AgriHeconomicsTermTotal { get; set; }
        public int? AgriHeconomicsTerm { get; set; }
        public int? EnglishAggregateTotal { get; set; }
        public int? EnglishAggregate { get; set; }
        public int? UrduAggregateTotal { get; set; }
        public int? UrduAggregate { get; set; }
        public int? ArabicAggregateTotal { get; set; }
        public int? ArabicAggregate { get; set; }
        public int? MathematicsAggregateTotal { get; set; }
        public int? MathematicsAggregate { get; set; }
        public int? ScienceAggregateTotal { get; set; }
        public int? ScienceAggregate { get; set; }
        public int? SocialStudiesAggregateTotal { get; set; }
        public int? SocialStudiesAggregate { get; set; }
        public int? IslamiatAggregateTotal { get; set; }
        public int? IslamiatAggregate { get; set; }
        public int? ComputerAggregateTotal { get; set; }
        public int? ComputerAggregate { get; set; }
        public int? QuranAggregateTotal { get; set; }
        public int? QuranAggregate { get; set; }
        public int? BehaviorAggregateTotal { get; set; }
        public int? BehaviorAggregate { get; set; }
        public int? PhysicsAggregateTotal { get; set; }
        public int? PhysicsAggregate { get; set; }
        public int? ChemistryAggregateTotal { get; set; }
        public int? ChemistryAggregate { get; set; }
        public int? BiologyAggregateTotal { get; set; }
        public int? BiologyAggregate { get; set; }
        public int? AgriHeconomicsAggregateTotal { get; set; }
        public int? AgriHeconomicsAggregate { get; set; }
        public int? AggregateTotal { get; set; }
        public int? AggregateObtained { get; set; }
        public string? Grade { get; set; }
        public int? PositionOverall { get; set; }
        public int? PositionClass { get; set; }
        public string? Remarks { get; set; }
        public string StuName { get; set; } = null!;
        public string ClassName { get; set; } = null!;
        public string? StuRegNumber { get; set; }
    }
}
